# Generated by Django 4.1.6 on 2023-04-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0002_alter_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fnacim',
            field=models.DateField(null=True),
        ),
    ]
