# Generated by Django 4.1.6 on 2023-04-17 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0004_alter_usuario_apellido_alter_usuario_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('denunciado', models.CharField(max_length=40)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warmikuna_app.usuario')),
            ],
        ),
    ]
