# Generated by Django 4.2.1 on 2023-06-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0006_remove_denuncia_imagenes_denuncia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='passwordResetToken',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
