# Generated by Django 4.2.1 on 2023-06-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0007_usuario_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('denuncia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warmikuna_app.denuncia')),
            ],
        ),
    ]
