# Generated by Django 4.2.1 on 2023-06-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0008_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='id_anonimo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
