# Generated by Django 4.2.1 on 2023-06-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0010_denuncia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('E1', 'Enviado'), ('E2', 'En investigación'), ('E3', 'Archivado'), ('E4', 'Cerrado'), ('E5', 'Requiere más datos')], default='E1', max_length=20),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id_anonimo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
