# Generated by Django 4.2.1 on 2023-06-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0011_alter_denuncia_estado_alter_denuncia_id_anonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('E1', 'Enviado'), ('E2', 'En investigación'), ('E3', 'Archivado'), ('E4', 'Cerrado'), ('E5', 'Requiere más datos')], default='Enviado', max_length=20),
        ),
    ]
