# Generated by Django 4.2.1 on 2023-06-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0012_alter_denuncia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('En investigación', 'En investigación'), ('Archivado', 'Archivado'), ('Cerrado', 'Cerrado'), ('Requiere más datos', 'Requiere más datos')], default='Enviado', max_length=20),
        ),
    ]
