# Generated by Django 4.2.1 on 2023-06-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0013_alter_denuncia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TallerXUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warmikuna_app.taller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warmikuna_app.usuario')),
            ],
        ),
    ]
