# Generated by Django 4.2.1 on 2023-06-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0014_taller_tallerxusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
