# Generated by Django 4.2.1 on 2023-06-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0015_alter_taller_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='motivo',
            field=models.CharField(choices=[('Abuso', 'Abuso'), ('Acoso', 'Acoso'), ('Maltrato', 'Maltrato')], default='Abuso', max_length=20),
        ),
    ]
