# Generated by Django 4.2.1 on 2023-07-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0016_denuncia_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallerxusuario',
            name='comentario',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
