# Generated by Django 4.2.1 on 2023-07-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0017_tallerxusuario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='departamento',
            field=models.CharField(choices=[('Lima', 'Lima'), ('Arequipa', 'Arequipa'), ('Cusco', 'Cusco'), ('La Libertad', 'La Libertad'), ('Piura', 'Piura'), ('Lambayeque', 'Lambayeque'), ('Junín', 'Junín'), ('Puno', 'Puno'), ('Ancash', 'Ancash'), ('Ica', 'Ica'), ('Tacna', 'Tacna'), ('Loreto', 'Loreto'), ('Ucayali', 'Ucayali'), ('San Martín', 'San Martín'), ('Madre de Dios', 'Madre de Dios'), ('Amazonas', 'Amazonas'), ('Pasco', 'Pasco'), ('Huancavelica', 'Huancavelica'), ('Ayacucho', 'Ayacucho'), ('Tumbes', 'Tumbes'), ('Moquegua', 'Moquegua'), ('Huánuco', 'Huánuco'), ('Apurímac', 'Apurímac'), ('Cajamarca', 'Cajamarca'), ('Callao', 'Callao'), ('Iquitos', 'Iquitos')], default='Lima', max_length=50),
        ),
    ]
