# Generated by Django 4.2.1 on 2023-07-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warmikuna_app', '0018_denuncia_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warmikuna_app.usuario'),
        ),
    ]
